// <auto-generated />
namespace Contentmanagementsystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class modify_contacts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modify_contacts));
        
        string IMigrationMetadata.Id
        {
            get { return "202406090950227_modify_contacts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
